#!/bin/bash
set -e
cd "$(dirname "$0")"

if [ -d /usr/share/openfoam/etc ]; then
    export FOAM_ETC=/usr/share/openfoam/etc
    export WM_PROJECT_DIR=/usr/share/openfoam
    export WM_PROJECT=OpenFOAM
    export FOAM_APPBIN=/usr/bin
    export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
elif ls /opt/openfoam*/etc/bashrc >/dev/null 2>&1; then
    source $(ls /opt/openfoam*/etc/bashrc | head -n 1)
elif ls /usr/lib/openfoam/openfoam*/etc/bashrc >/dev/null 2>&1; then
    source $(ls /usr/lib/openfoam/openfoam*/etc/bashrc | head -n 1)
fi

blockMesh
surfaceFeatureExtract || true
snappyHexMesh -overwrite
checkMesh
simpleFoam
foamToVTK -ascii || true
